/**
 * Auto-generated CRUD Operations from Entity Config
 * 
 * This file is AUTO-GENERATED by 'yarn generate-entities'
 * DO NOT EDIT MANUALLY - changes will be overwritten!
 * 
 * To add/modify entities, edit src/lib/db/entities.config.ts
 * then run 'yarn generate-entities'
 */

import { createCrud } from './crud-factory';
import { entities } from './entities.config';

// Generate CRUD operations for savedItems
const savedItemsCrud = createCrud(entities.savedItems);

export const getAllSavedItems = savedItemsCrud.getAll;
export const getSavedItems = savedItemsCrud.getById;
export const createSavedItems = savedItemsCrud.create;
export const updateSavedItems = savedItemsCrud.update;
export const deleteSavedItems = savedItemsCrud.delete;

