/**
 * Database Entity Registry
 * 
 * This file is AUTO-GENERATED by 'yarn generate-entities'
 * DO NOT EDIT MANUALLY - changes will be overwritten!
 * 
 * Usage:
 *   import { db } from '$lib/db/registry';
 *   const items = await db.entityName.getAll();
 *   await db.entityName.create({ ... });
 */

import {
	getAllSavedItems,
	getSavedItems,
	createSavedItems,
	updateSavedItems,
	deleteSavedItems,
} from './entities.remote';

export const db = {
	savedItems: {
		getAll: getAllSavedItems,
		getById: getSavedItems,
		create: createSavedItems,
		update: updateSavedItems,
		delete: deleteSavedItems
	},
};

// Type-safe access to all entities
export type DbEntity = keyof typeof db;
