-- Auto-generated migration for savedItems
-- Generated by 'yarn generate-entities'

CREATE TABLE IF NOT EXISTS saveditems (
	id SERIAL PRIMARY KEY,
	slug TEXT NOT NULL,
	created_at TIMESTAMP DEFAULT NOW()
);
